version: '3.4'

services:
  bootstrapper:
    image: ${DOCKER_REGISTRY-}bootstrapper
    build:
      context: .
      dockerfile: src/Bootstrapper/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: mysuperpass!
      ACCEPT_EULA: "Y"