version: '3.4'

services:
  bootstrapper:
    image: ${DOCKER_REGISTRY-}bootstrapper
    ports:
      - "44360:80"
    build:
      context: ../src
      dockerfile: ../src/Dockerfile
    depends_on:
      - db
  db:
    image: "postgres" # use latest official postgres version
    env_file:
      - .env # configure postgres
#    volumes:
#      - database-data:/var/lib/postgresql/data/ # persist data even