name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: workaround. remove docker-compose project
      run: dotnet sln StoreKit.sln remove docker-compose/docker-compose.dcproj
    - name: Restore dependencies
      run: dotnet restore StoreKit.sln
    - name: Build
      run: dotnet build StoreKit.sln --no-restore
    - name: Test
      run: dotnet test StoreKit.sln --no-build --verbosity normal
